services:
  - type: web
    name: Ai-complaint-classifier
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn --chdir backend app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGINS
        value: "*"
      - key: SECRET_KEY
        generateValue: true
